version: "3.8"

services:
  api:
    build:
      context: ../back-end-educa-facil
      dockerfile: Dockerfile
    container_name: nest_api
    restart: always
    depends_on:
      - db
      - rabbitmq
    ports:
      - "3000:3000"
