version: '3.8'

services:
  api:
    build: 
      context: ../back-end-educa-facil
      dockerfile: Dockerfile
    container_name: nest_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://nest_user:nest_password@db:5432/nest_db
    ports:
      - "3000:3000"
