name: Lint & Type-check

on:
  push:
    branches: [main]
    paths:
      - 'back-end-educa-facil/**'
  pull_request:
    branches: [main]
    paths:
      - 'back-end-educa-facil/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install deps
        working-directory: back-end-educa-facil
        run: pnpm install --frozen-lockfile

      - name: ESLint
        working-directory: back-end-educa-facil
        run: pnpm lint

      - name: Type-check
        working-directory: back-end-educa-facil
        run: pnpm tsc --noEmit