name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Instalar pnpm manualmente
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh
          export PATH="$HOME/.local/share/pnpm:$HOME/.npm-global/bin:$PATH"
          echo "PATH atualizado: $PATH"

      - name: Verificar instalação do pnpm
        run: pnpm --version

      - name: Instalar dependências
        working-directory: back-end-educa-facil
        run: pnpm install --frozen-lockfile

      - name: Rodar testes
        working-directory: back-end-educa-facil
        run: pnpm test

      - name: Fazer build da aplicação
        working-directory: back-end-educa-facil
        run: pnpm build