name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          check-latest: true

      - name: Instalar pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          echo "pnpm instalado em: $(which pnpm)"
          
      - name: Verificar instalação do pnpm
        run: pnpm --version

      - name: Instalar dependências
        working-directory: back-end-educa-facil
        run: pnpm install --frozen-lockfile

      - name: Rodar testes
        working-directory: back-end-educa-facil
        run: pnpm test

      - name: Fazer build da aplicação
        working-directory: back-end-educa-facil
        run: pnpm build